Add --no-withdrawl flag for "canister delete" for when the canister is out of cycles
dfinity/sdk pull request #1907
Opened 2021-11-09 03:10 UTC by jplevyak

Note: the reject enum is too small (ReplicaError is all we get) to differentiate when a call fails because
the canister is out of cycycles.

If instead we passed from the ic repo: rs/types/error_types/src/lib.rs ErrorCode::OutOfCycles (code 501) back
we could use that to handle that case and automatically fallback to a simple delete.

Signed-off-by: John Plevyak <jplevyak@gmail.com>

2021-11-09 16:02 UTC, ericswanson-dfinity requested changes
Let's start by fixing a spelling error in the new argument name

2021-11-17 00:20 UTC, jplevyak commented on src/dfx/src/commands/canister/delete.rs
> +    no_withdrawl: bool,
done and below

2021-11-17 18:40 UTC, ericswanson-dfinity commented
Would you please add an entry to the [changelog](https://github.com/dfinity/sdk/blob/master/CHANGELOG.adoc)?

2021-11-17 19:23 UTC, ericswanson-dfinity approved these changes

2021-11-17 20:34 UTC, jplevyak commented
Added changelog entry.

2021-11-18 18:32 UTC, merged