feat: support canister sandboxing
dfinity/sdk pull request #1994
Opened 2022-01-25 11:24 UTC by ulan

This adjusts the scripts to download the `canister_sandboxing`
binary, which is a dependency of the `replica` binary.

Note that the current version of the replic from Dec 10 does not
have canister sandboxing flag enabled, so the downloaded
`canister_sandbox` binary is not used.

The next update of the replica binary will enable canister
sandboxing on Linux and will start using the corresponding
`canister_sandbox` binary.

2022-01-25 18:20 UTC, ericswanson-dfinity commented on scripts/dfx-asset-sources.sh
> +# The replica and canister_sandbox binaries must have the same revision.
If you want these comments to be in this file, scripts/write-dfx-asset-sources.sh will have to output them.

2022-01-25 18:21 UTC, ericswanson-dfinity requested changes
There's a CI check failure (because the output of scripts/write-dfx-asset-sources.sh doesn't match the contents of scripts/dfx-asset-sources.sh).

Would you also please update the instructions in https://github.com/dfinity/sdk/blob/master/.github/CONTRIBUTING.adoc#updating-the-replica ?

2022-01-26 17:54 UTC, ericswanson-dfinity commented on scripts/dfx-asset-sources.sh
> +CANISTER_SANDBOX_X86_64_LINUX_URL="https://download.dfinity.systems/blessed/ic/75138bbf11e201aac47266f07bee289dc18a082b/release/canister_sandbox.gz"
These values have to be added by `scripts/write-dfx-asset-sources.sh`, which happens here: https://github.com/dfinity/sdk/blob/master/scripts/write-dfx-asset-sources.sh#L65

2022-01-26 18:49 UTC, ericswanson-dfinity approved these changes

2022-01-26 20:49 UTC, merged

2022-01-27 08:07 UTC, ulan commented
Thanks @ericswanson-dfinity for fixing the PR and merging it! I was OOO yesterday.