fix: dfx new --no-frontend should not create an assets container
dfinity/sdk pull request #2020
Opened 2022-02-11 00:09 UTC by rikonor

See https://github.com/dfinity/sdk/issues/1648

This change introduces the use of Handlebars templates to control whether dfx.json contains an assets container via the `--no-frontend` flag.

There is still the issue that the resulting project has a `src/<name>_assets` directory with a dummy text file.

Another approach would be to instead of dynamically generating a project directory, allow using pre-made example projects (See [Next.js example](https://nextjs.org/docs/api-reference/create-next-app#options)).
This would deprecate `--type [motoko, rust]` and `--frontend` / `--no-frontend`.
Instead, provide a default project (e.g motoko-based) vendored with `dfx` but also allow specifying an `--example` arg.

2022-05-04 15:28 UTC, ali-dfinity commented
/bot update

2022-07-28 21:08 UTC, krpeacock approved these changes

2022-07-28 23:47 UTC, ericswanson-dfinity requested changes

2022-07-28 23:47 UTC, ericswanson-dfinity commented on e2e/tests-dfx/bootstrap.bash
> -@test "bootstrap supports http requests" {
Can we use `dfx_new_frontend` here, and keep this test?  Same for the other removed tests in this PR.

2022-07-28 23:48 UTC, ericswanson-dfinity commented on .github/workflows/e2e.yml
> -          time curl --fail http://localhost:8000/sample-asset.txt?canisterId=$(dfx canister id smoke_frontend)
Can we create this project with a frontend?  Ensuring that a basic project can serve assets is an important part of the "smoke" test.

2024-05-03 18:47 UTC, closed without merging