chore: move asset-canister-related crates into SDK repo
dfinity/sdk pull request #2412
Opened 2022-08-05 13:08 UTC by smallstepman

# Description

Move all asset-canister-related code into the SDK repo. This includes:
- `ic-asset`
- `icx-asset`
- `ic-certified-assets`
- `certified-assets` 

Closes [SDK-607](https://dfinity.atlassian.net/browse/SDK-607)

# TODO

- [ ] CI/CD - GitHub Actions 
- [ ] tests
- [ ] figure out what to do with `/src/distributed/assetstorage.{did,wasm}` - remember these files are included in the build process of SDK via `/src/dfx/assets/build.rs`

# How Has This Been Tested?

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2022-08-18 19:21 UTC, ericswanson-dfinity requested changes
Should this PR also update these crate dependencies?
- https://github.com/dfinity/sdk/blob/master/src/dfx/Cargo.toml#L90
- https://github.com/dfinity/sdk/blob/master/Cargo.toml#L11

2022-08-18 19:21 UTC, ericswanson-dfinity commented on .github/workflows/update-docs.yml
> +        run: cargo build
```suggestion
        run: cargo build
```

2022-08-18 19:49 UTC, smallstepman commented
@ericswanson-dfinity amazing as always to see you catch all of that

I had this change in other PR, but forgot to add it here

fixed

2022-08-18 19:52 UTC, smallstepman commented
what do you think about dir name `src/assets_canister`? underscore vs hyphen? `assets` vs `asset`?

2022-08-18 21:23 UTC, ericswanson-dfinity requested changes
I notice this when I run `cargo clean` and so forth. 
```
$ cargo clean
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/ericswanson/d/sdk/src/canisters/frontend/certified-assets/Cargo.toml
workspace: /Users/ericswanson/d/sdk/Cargo.toml
```

2022-08-18 21:23 UTC, ericswanson-dfinity commented on src/canisters/frontend/certified-assets/Cargo.toml
> +ic-certified-assets = { path = "../ic-certified-assets", vesrion = "0.2.4" }
typo
```suggestion
ic-certified-assets = { path = "../ic-certified-assets", version = "0.2.4" }
```

2022-08-22 15:36 UTC, smallstepman commented on src/canisters/frontend/certified-assets/Cargo.toml
> +ic-certified-assets = { path = "../ic-certified-assets", vesrion = "0.2.4" }
got rid of `version` altogether

2022-08-22 15:40 UTC, smallstepman commented
@ericswanson-dfinity thanks, fixed it here https://github.com/dfinity/sdk/pull/2412/commits/676c2aac597ecee469eb5dba6cd545e80c479318

For some reason, it's not possible to specify `panic`/`lto`/`rpath` in root level Cargo package-specific profile overrides section
```
[profile.<name>.package.<name>]  # Override profile for a package.
# Same keys for a normal profile (minus `panic`, `lto`, and `rpath`).
```
so I had to make a global one (`[profile.release]`)

2022-08-22 17:03 UTC, ericswanson-dfinity approved these changes

2022-08-23 15:02 UTC, merged