feat: Add --argument-file option to dfx canister sign
dfinity/sdk pull request #2787
Opened 2022-11-29 19:49 UTC by Maximkaaa

# Description

`dfx canister call` command has an argument `--argument-file` to allow sending the request when argument string is too long for shell. `dfx canister sign` command didn't have this argument so some of the requests possible by `dfx canister call` were not possible to be executed through sign/send workflow. This PR fixes this unfortunate inconvenience:

* add `--argument-file` option to `sign` command
* move the logic related to reading argument string from a file from `call` command to utils so that it can be reused by both `call` and `sign`
* refactor the logic a little to use correct error handling instead of `expect`s

# How Has This Been Tested?

Added e2e test cases. Also did signing manually with compiled `dfx`, including some very long argument strings that didn't fit into CLI arguments.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] I have made corresponding changes to the documentation.

2022-11-30 09:17 UTC, sesi200 requested changes
Thank you very much for such a complete PR! Even changes to the docs are included!

I have a few small suggestions for the tests, otherwise this looks great.

2022-11-30 09:17 UTC, sesi200 commented on docs/cli-reference/dfx-canister.md
> +| `--argument-file`          | Specifies the file from which to read the argument to pass to the method.  Stdin may be referred to as `-`.                                      |
```suggestion
| `--argument-file <file>`   | Specifies the file from which to read the argument to pass to the method.  Stdin may be referred to as `-`.                                      |
```

2022-11-30 09:17 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +@test "call subcommand accepts argument from a file" {
```suggestion
@test "sign subcommand accepts argument from a file" {
```

2022-11-30 09:17 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +@test "call subcommand accepts argument from stdin" {
```suggestion
@test "sign subcommand accepts argument from stdin" {
```

2022-11-30 09:17 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +
```suggestion

    echo y | assert_command dfx canister send message.json
    # cbor-encoded response that says "Hello, stdin!"
    assert_match "d9d9f7a266737461747573677265706c696564657265706c79a163617267554449444c0001710d48656c6c6f2c20737464696e21"

```

let's check that the argument was actually included in the message

2022-11-30 09:17 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +
```suggestion

    echo y | assert_command dfx canister send message.json
    # cbor-encoded response that says "Hello, Names can be very long!"
    assert_match "d9d9f7a266737461747573677265706c696564657265706c79a16361726758264449444c0001711e48656c6c6f2c204e616d65732063616e2062652076657279206c6f6e6721"

```

let's check that the argument was actually included in the message

2022-11-30 09:28 UTC, Maximkaaa commented
Thanks for the quick review and suggestions. Yes, I also wanted to check the sign result in the tests but was not sure how to go about it.

2022-11-30 09:39 UTC, sesi200 commented
I'm not 100% sure this works either, but I think it should. Would you mind going through the CLA bot process? Otherwise I'm not allowed to merge this. (Also, can you do it for both issues? It has a bug where it duplicates everything and if you just go through it for both issues it opened it's quickest)

2022-11-30 09:57 UTC, sesi200 reviewed
This should fix the sign_send test failures

2022-11-30 09:57 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +    dfx_deploy
```suggestion
    dfx deploy
```

2022-11-30 09:57 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +    dfx_deploy
```suggestion
    dfx deploy
```

2022-11-30 11:40 UTC, Maximkaaa commented
@sesi200 I applied the suggested change and completed cla process in both issues.

2022-11-30 11:52 UTC, sesi200 commented
Thanks a lot, @Maximkaaa. I'll only have to get #2788 merged, and then this is good to merge, too

2022-11-30 12:24 UTC, sesi200 approved these changes

2022-11-30 12:43 UTC, sesi200 requested changes

2022-11-30 12:43 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +    assert_command dfx canister sign --argument-file "$TMP_NAME_FILE" --query hello_backend
```suggestion
    assert_command dfx canister sign --argument-file "$TMP_NAME_FILE" --query hello_backend greet
```
missing method name

2022-11-30 12:43 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +    echo y | assert_command dfx canister send message.json
```suggestion
    echo y | dfx canister send message.json > out.txt
    assert_command cat out.txt
```
sorry, need to correct it again. This time I tested it locally

2022-11-30 12:43 UTC, sesi200 commented on e2e/tests-dfx/sign_send.bash
> +    echo y | assert_command dfx canister send message.json
```suggestion
    echo y | dfx canister send message.json > out.txt
    assert_command cat out.txt
```
same here

2022-11-30 14:26 UTC, Maximkaaa commented
I've fixed the last e2e test. The difference between expected and actual was due to the ordering of fields in the json, actual message is same.

2022-11-30 16:17 UTC, sesi200 approved these changes

2022-11-30 17:24 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +Similar to how this argument works in `dfx canister call`, this argument allows providing arguments for the requst from a file.
```suggestion
Similar to how this argument works in `dfx canister call`, this argument allows providing arguments for the request from a file.
```

2022-12-01 06:27 UTC, Maximkaaa commented
It seems that the order of fields in the response is not fixed so the tests flicker. So I changed the approach to checking the signed values. Instead of sending and checking the response, why not just check the arguments in the signed message file?

2022-12-01 08:12 UTC, merged

2022-12-01 08:13 UTC, sesi200 commented
That works as well. Thanks!