build: extend script/update-frontend-canister.sh
dfinity/sdk pull request #2814
Opened 2022-12-12 21:18 UTC by smallstepman

adds a help message and two flags:
```
   -d, --development-build    build canister using cargo
   -r, --release-build        build canister using linux/amd64 docker image
   -h, --help                 print this help message
```

When working on macOS ARM, building frontend canister using linux/amd64 docker image takes a while. This script adds an option to build the frontend canister the old way - using Rust and ic-wasm that are locally installed, this speeds up the build time significantly (useful when working on e2e tests)

2022-12-12 22:49 UTC, ericswanson-dfinity requested changes
Why is src/distributed/assetstoreage.wasm.gz changed in this PR?

2022-12-12 22:52 UTC, ericswanson-dfinity commented on scripts/update-frontend-canister.sh
> +   echo "  -r, --release-build        build canister using linux/amd64 docker image"
Please update CONTRIBUTING.md and .github/workflows/build-frontend-canister.yml with the release build option

2022-12-12 23:31 UTC, ericswanson-dfinity commented on .github/workflows/build-frontend-canister.yml
> +            echo "src/distributed/assetstorage.wasm.gz needs to be updated; run ./scripts/update-frontend-canister.sh --release_build"
```suggestion
            echo "src/distributed/assetstorage.wasm.gz needs to be updated; run ./scripts/update-frontend-canister.sh --release-build"
```

2022-12-12 23:34 UTC, ericswanson-dfinity requested changes

2022-12-12 23:34 UTC, ericswanson-dfinity commented on scripts/update-frontend-canister.sh
> +    fi
```
$ ./scripts/update-frontend-canister.sh --development-build
./scripts/update-frontend-canister.sh: line 34: CARGO_HOME: unbound variable
```

2022-12-13 09:41 UTC, smallstepman commented on scripts/update-frontend-canister.sh
> +    fi
🙄

2022-12-13 19:48 UTC, ericswanson-dfinity approved these changes

2022-12-13 21:35 UTC, merged