refactor(e2e): embed `bats-support` as git submodule
dfinity/sdk pull request #2967
Opened 2023-02-13 18:04 UTC by smallstepman

# Description

Instead of depending on locally installed (and outdated) `bats-support`, we can now embed it as a git submodule ([which is the currently recommended way of installing bats](https://bats-core.readthedocs.io/en/stable/tutorial.html#quick-installation)).
This removes the need to `export BATSLIB=...` and installing it in the first place.
In order to take advantage of new setup, `sdk` repository needs to be pulled with submodules:
- for already cloned repositories:
   ```bash
   cd sdk
   git submodule update --init --recursive
   ```
- when cloning fresh:
   ```bash
   git clone --recursive git://github.com/dfinity/sdk.git
   ``` 

# How Has This Been Tested?

Covered by CI

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly. 
- [x] I have made corresponding changes to the documentation.

2023-02-13 21:05 UTC, krpeacock commented
The tests are still failing to run for me locally, but bats works like a charm now!

<img width="854" alt="image" src="https://user-images.githubusercontent.com/16298804/218574279-0d055479-e1df-4579-bbb7-8df4f98ec0c6.png">

2023-02-21 08:23 UTC, ericswanson-dfinity requested changes

2023-02-21 08:23 UTC, ericswanson-dfinity commented on .github/CONTRIBUTING.md
> +1. Download all of this repository' submodules (which includes `bats-suppor`)
```suggestion
1. Download all of this repository' submodules (which includes `bats-support`)
```

2023-02-21 23:47 UTC, ericswanson-dfinity approved these changes
Nice!

2023-02-21 23:47 UTC, merged

2023-02-21 23:47 UTC, ericswanson-dfinity approved these changes
Nice!