feat(extensions): add `--install-as` flag to `dfx extension install` command
dfinity/sdk pull request #2998
Opened 2023-03-02 18:20 UTC by smallstepman

# Description

Continuation of https://github.com/dfinity/sdk/pull/2968. Allows to install extension under different name, which should help with naming conflicts resolution.

# How Has This Been Tested?

```console
❯ cargo run -- extension install sns --install-as snsns
   Compiling dfx v0.14.1 
    Finished dev [unoptimized + debuginfo] target(s) in 4.93s
     Running `target/debug/dfx extension install sns --install-as snsns`
  Extension 'sns' installed successfully, and is available as 'snsns'

❯ cargo run snsns                                   
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/dfx snsns`
error: 'snsns' requires a subcommand but one was not provided
  [subcommands: config, deploy, import, download, help]

Usage: snsns [OPTIONS] <COMMAND>

For more information, try '--help'.
Error: Extension exited with non-zero status code '2'.
```

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2023-06-05 11:07 UTC, ericswanson-dfinity requested changes
This feature seems like an unnecessary complication.  We can revisit in the future if the perceived utility exceeds "should help with".

2023-06-05 12:08 UTC, smallstepman commented
Actually, there have been several occasions where I worked with extensions and wished this was already merged. I'd use that for installing `sns` extension, even when `dfx sns` command already exists (i.e. `dfx extension install sns --install-as sns-dev`) - very useful for testing things. I definitely don't see it as an unnecessary complication

2023-06-05 12:49 UTC, ericswanson-dfinity commented
Okay, then let's try some DRY so that there will be fewer differences to maintain.

2023-06-16 07:20 UTC, ericswanson-dfinity requested changes

2023-06-16 07:20 UTC, ericswanson-dfinity commented on src/dfx/src/commands/extension/install.rs
> +                format!(", and is available as '{}'", opts.install_as.unwrap())
if let Some() to avoid unwrap

2023-06-16 07:20 UTC, ericswanson-dfinity commented on src/dfx/src/lib/extension/manager/install.rs
> +        dbg!(std::fs::read_dir(temp_dir.path()).unwrap().count());
intentional to leave this in?

2023-06-16 12:54 UTC, ericswanson-dfinity approved these changes

2023-06-16 13:14 UTC, merged