feat: specify id when provisional create canister
dfinity/sdk pull request #3021
Opened 2023-03-14 20:28 UTC by lwshang

# Description

When create canister on non-mainnet replica, you can now specify the canister ID.

`dfx canister create <CANISTER_NAME> --specified-id <PRINCIPAL>`

`dfx deploy <CANISTER_NAME> --specified-id <PRINCIPAL>`

Close SDK-803

# How Has This Been Tested?

e2e

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2023-03-14 23:45 UTC, ericswanson-dfinity requested changes

2023-03-14 23:45 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +When create canister on non-mainnet replica, you can now specify the canister ID.
```suggestion
When creating a canister on non-mainnet replica, you can now specify the canister ID.
```

2023-03-14 23:45 UTC, ericswanson-dfinity commented on src/dfx/src/commands/canister/create.rs
> +                // TODO: create for pull canisters with their mainnet ID
Is there a JIRA ticket that tracks this TODO? If so, please link to it in this comment. If not, please create one.

2023-03-14 23:45 UTC, ericswanson-dfinity commented on src/dfx/src/lib/operations/canister/create_canister.rs
> +                    dbg!(&res);
```suggestion
```

2023-03-15 17:52 UTC, ericswanson-dfinity approved these changes

2023-03-15 18:31 UTC, merged

2023-03-23 18:56 UTC, LiveDuo commented
> Any plans to support configuring a CID in dfx.json?

This is very welcome for setting up ledger, cmc or II locally. Currently it's quite a hassle.

2023-03-23 20:18 UTC, lwshang commented
> setting up ledger, cmc or II locally.
@LiveDuo Could you give `dfx nns install` a try? It set system canisters locally.

"configuring a CID in dfx.json" is on our plan. It will firstly be in the upcoming `dfx pull` feature. For more general usage, we need design an intuitive workflow first.

2023-03-23 21:12 UTC, LiveDuo commented
> > setting up ledger, cmc or II locally.
> 
> @LiveDuo Could you give `dfx nns install` a try? It set system canisters locally.
> 
> "configuring a CID in dfx.json" is on our plan. It will firstly be in the upcoming `dfx pull` feature. For more general usage, we need design an intuitive workflow first.

When it deploys the ledger canister who gets the initial distribution of the ICP?

PS: out of curiosity what's the `dfx pull` command for?

2023-03-23 21:23 UTC, lwshang commented
You can specify the accounts as below:
https://github.com/dfinity/sdk/blob/900f9f016fb0b3622af536ef2b5eaffc60c4a14f/e2e/tests-dfx/ledger.bash#L17

`dfx pull` will help you to pull canisters (and their dependencies) from mainnet. Then you can install them locally at the same canister ID. It will simplify the procedure to integrate with other canisters (ledger, cmc, "some DEX", etc).
Check this file https://github.com/dfinity/sdk/blob/master/e2e/assets/pull/dfx.json to get an impression on how to specify dependency canisters to be pulled from mainnet.

2023-03-23 21:28 UTC, LiveDuo commented
Thanks.

Ideally `dfx nns install` should be a flag in dfx.json too. I expect some projects using the nns canisters needing it all the time.

The `dfx pull` command should be great for e2e tests. Glad to learned about it.