refactor(dfx): `crate::lib::project` concrete error types
dfinity/sdk pull request #3039
Opened 2023-03-22 15:53 UTC by smallstepman

# Description

Concrete error types for `crate::lib::project::{import, network_mappings}`

In preparation to move to `dfx-core` crate.

# How Has This Been Tested?

Covered by CI.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] ~I have edited the CHANGELOG accordingly.~
- [ ] ~I have made corresponding changes to the documentation.~

2023-03-22 18:39 UTC, ericswanson-dfinity requested changes
project/import can probably move into the nns/sns extensions, and we can remove the beta project import commands.  This code wouldn't move to dfx-core.

2023-03-22 19:00 UTC, smallstepman commented
I think it's still beneficial to pursue merging this because:
- https://dfinity.atlassian.net/browse/SDK-566 mentions we should modularize `dfx`. Even if this stuff cannot go to `dfx-core`, I'd argue the functionality is enough generic to be worthy of putting into a separate crate instead of being baked into `nns` extension "forever", instead, we could put it into `dfx-extensions-core` or `dfx-project` crate.
- improves over current error messages

2023-03-22 19:33 UTC, ericswanson-dfinity approved these changes
🤷‍♂️ Okay, but please don't try to move this to dfx-core.

2023-03-22 19:35 UTC, smallstepman reviewed
figure out these TODOs before merging

2023-03-22 19:35 UTC, smallstepman commented on src/dfx/src/lib/error/project.rs
> +    // Q: ok to handle Infallible?
TODO

2023-03-22 21:35 UTC, ericswanson-dfinity requested changes

2023-03-23 17:30 UTC, ericswanson-dfinity approved these changes

2023-03-23 18:58 UTC, merged