Update to clap v4
dfinity/sdk pull request #3115
Opened 2023-05-03 17:28 UTC by adamspofford-dfinity

This updates clap to v4. Notable changes:

- Argument IDs are no longer case-converted in code; `foo_bar` means `conflicts_with("foo_bar")`, not `"foo-bar"`.
- 'Validators' have been replaced with parsers, to eliminate our habit of parsing twice.
- ArgAction replaces a number of special-cased functions like from_occurrences. 

The full high-level changelog can be found [here](https://epage.github.io/blog/2022/09/clap4/). 

This PR would have been delayed longer until `unstable-colors` is no longer unstable, but v3 blocks work by @smallstepman, so we should instead just be careful about updating clap in the lockfile. Also, these are more or less the default colors from v3, but we might want to look into using brand colors in certain places.

2023-05-03 17:35 UTC, smallstepman reviewed
shouldn't we use `arg` instead of `clap`? https://docs.rs/clap/latest/clap/index.html

2023-05-03 17:35 UTC, smallstepman commented on src/dfx/src/commands/beta/project/import.rs
> +    #[clap(long, required_unless_present("canister_name"))]
```suggestion
    #[arg(long, required_unless_present("canister_name"))]
```

2023-05-03 19:02 UTC, smallstepman commented
since we're using `clap` as a workspace dependency, I think we should also update `icx-asset` (`#[clap` -> `#[arg/command`)

2023-05-03 19:11 UTC, adamspofford-dfinity commented
It will be breaking in v5, but they're not emitting deprecation warnings for it.

2023-05-03 23:16 UTC, ericswanson-dfinity approved these changes

2023-05-04 15:31 UTC, smallstepman requested changes
looks like text wrapping for help command is behind feature flag now, you probably didn't notice on your widescreen ;) 
![Screenshot 2023-05-04 at 17 30 03](https://user-images.githubusercontent.com/21069150/236255999-697e2427-5523-43fe-8628-3ca3d1799db7.png)

2023-05-04 15:31 UTC, smallstepman commented on src/canisters/frontend/icx-asset/Cargo.toml
> +clap = { workspace = true, features = ["derive", "cargo", "unstable-styles"] }
```suggestion
clap = { workspace = true, features = ["derive", "cargo", "unstable-styles", "wrap_help" ] }
```

2023-05-05 09:27 UTC, smallstepman approved these changes

2023-05-08 20:20 UTC, merged