feat: dfx canister url
dfinity/sdk pull request #3346
Opened 2023-09-01 19:48 UTC by krpeacock

# Description

Adds a new canister subcommand - `dfx canister url`
```
Prints the URL of a canister

Usage: dfx canister url [OPTIONS] <CANISTER>

Arguments:
  <CANISTER>  Specifies the name of the canister
```

this feature allows developers to easily produce a url for a canister for a given network. The logic works as follows:

 - frontend canisters will use the ?canisterId query parameter for local urls
 - frontend canisters will point to <canister-id>.icp0.io for mainnet
 - backend canisters will link to the Candid UI frontend for the specified network, with the interface for the canister

This logic is largely provided in `dfx-core`, and the formatting is shared for both `dfx deploy` and `dfx canister url` output

# How Has This Been Tested?

Newly added unit and e2e tests cover this feature

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2023-09-01 21:27 UTC, ericswanson-dfinity requested changes
Please consider reverting all of the changes to `construct_frontend_url` (the ic0.app renaming, the localhost special-casing) and `construct_ui_canister_url`.  Instead, open two PRs:
1. This PR, which:
    - refactors the frontend URL formatting methods by moving them as-is from `dfx deploy` to dfx-core
    - adds `dfx canister url` which also calls them
2. A new PR, which changes the behavior of the frontend URL formatting methods

Including both changes together in this PR makes them harder to review for two reasons:
- moving a method and changing it in the same PR looks like "deleted method A" and " added method B".  This makes it more difficult to look at only what changed.
- Conceptually they are two different changes: "added dfx canister url command" and "improved canister URLs [in these ways]".   Submitting them separately will make it easier to focus on the changes.

Please update https://github.com/dfinity/sdk/blob/master/docs/cli-reference/dfx-canister.md

2023-09-01 21:27 UTC, ericswanson-dfinity commented on src/dfx/src/commands/deploy.rs
> +                    let is_local = env.get_network_descriptor().name == "local";
What's the rationale in changing this logic?  This used to check `network.is_ic`, which matches the [condition for creating](https://github.com/dfinity/sdk/blob/master/src/dfx/src/lib/operations/canister/install_canister.rs#L58) the candid UI canister.

Also the name of `format_ui_canister_url_ic` is a hint: "do this on IC", not "do this unless the network name is 'local'"

2023-09-01 21:27 UTC, ericswanson-dfinity commented on src/dfx/src/commands/deploy.rs
>                      }
Please DRY
```suggestion
                    let url = if is_local {
                        let ui_canister_id = ui_canister_id.ok_or_else(|| {
                            anyhow!(
                                "The ui canister id is not set in the canister_id_store.json file."
                            )
                        })?;
                        format_ui_canister_url_custom(
                            &&canister_id.to_string(),
                            &provider,
                            &ui_canister_id.to_string(),
                        )
                    } else {
                        format_ui_canister_url_ic(&canister_id.to_string())?
                    };
                    candid_urls.insert(canister_name, url);
```

2023-09-01 21:27 UTC, ericswanson-dfinity commented on src/dfx-core/src/canister/url.rs
> +        if domain.ends_with("icp-api.io") || domain.ends_with("ic0.app") {
Looking for substrings in domain names is always iffy, but I suspect this should be the following:
```suggestion
        if domain == "icp-api.io" || domain.ends_with(".icp-api.io") || domain == "ic0.app" || domain.ends_with(".ic0.app") {
```

2023-09-01 21:27 UTC, ericswanson-dfinity commented on src/dfx-core/src/canister/url.rs
> +            let new_domain = new_domain.replace("ic0.app", "icp0.io");
Hostname manipulation is error-prone. What if the domain is `xyz-ic0.app-aaa.icp0.io`?

2023-09-01 21:32 UTC, ericswanson-dfinity commented on src/dfx-core/src/canister/url.rs
> +        } else if domain.contains("localhost") {
What if it's not-a-localhost.my-domain.yay

2025-06-20 00:24 UTC, raymondk commented
Closing this PR because it's too old

2025-06-20 00:24 UTC, closed without merging