fix: witness not provided for fallback on routes with an alias
dfinity/sdk pull request #3428
Opened 2023-10-31 10:15 UTC by sesi200

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2023-10-31 16:51 UTC, ericswanson-dfinity requested changes

2023-10-31 16:53 UTC, ericswanson-dfinity commented on src/canisters/frontend/ic-certified-assets/src/tests.rs
> +    let Ok(_) = verify_response(state, &request, &response) else {panic!("Response verification failed: {:#?}", response)};
Also I think it would be helpful to display (panic with) the ResponseVerificationError (inside the `Err`) as well as the response

2023-11-01 08:52 UTC, sesi200 commented on src/canisters/frontend/ic-certified-assets/src/tests.rs
> +    let Ok(_) = verify_response(state, &request, &response) else {panic!("Response verification failed: {:#?}", response)};
Thanks for catching that! New version reports all available information

2023-11-01 16:25 UTC, ericswanson-dfinity approved these changes

2023-11-02 07:15 UTC, merged