fix(ic-asset): .ic-assets.json `allow_raw_access` overrides
dfinity/sdk pull request #3434
Opened 2023-11-03 16:33 UTC by smallstepman

# Description

.ic-assets.json: "allow_raw_access" default overrides previous config entries even if not present in a match entry. This fixes the issue.
Fixes https://dfinity.atlassian.net/browse/SDK-1238

# How Has This Been Tested?

unit test

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [ ] ~I have made corresponding changes to the documentation.~

2023-11-03 18:18 UTC, ericswanson-dfinity commented on src/canisters/frontend/ic-asset/src/asset/config.rs
> +        if self.allow_raw_access.is_none() && other.allow_raw_access.is_some() {
Since `ignore`, `enable_aliasing`, and `cache` use the same logic, will they have the same problem?

2023-11-03 18:22 UTC, ericswanson-dfinity commented on src/canisters/frontend/ic-asset/src/asset/config.rs
> +        assert_eq!(x.allow_raw_access, y.allow_raw_access);
it's true that they should be the same, but we also expect them both to be `false`.  
```suggestion
        assert_eq!(x.allow_raw_access, false);
        assert_eq!(y.allow_raw_access, false);
```

2023-11-14 15:49 UTC, smallstepman commented on e2e/tests-dfx/assetscanister.bash
> -  "allow_raw_access": true
incorrectly introduced in #3369

2023-11-14 15:49 UTC, smallstepman commented on src/canisters/frontend/ic-asset/src/asset/config.rs
> +    #[default]
lint

2023-11-14 15:49 UTC, smallstepman commented on src/canisters/frontend/ic-asset/src/asset/config.rs
> +            }
makes life easier during debugging

2023-11-14 17:14 UTC, ericswanson-dfinity requested changes
Would you please write something in the PR description about _how_ this PR fixes the issue?  I see changes to use the `derivative` crate, but that looks like a refactor, not something that changes functionality.

Also please describe the problem that this solves in a little more detail in the PR description, since access to JIRA is not public.

2023-11-14 18:08 UTC, smallstepman commented
I pasted the content of jira ticket into pr description

2023-11-14 18:19 UTC, ericswanson-dfinity requested changes
Not to be merged until we understand how/why this PR fixes the issue.

2023-11-14 18:45 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +Fixed an issue where the `allow_raw_access` configuration value was being affected by the order of  declarations in the configuration file in `.ic-assets.json`.
In the changelog, please describe the issue in enough detail that someone with a project, the behavior of which will change after this fix, will be able to recognize that fact.

2023-11-14 18:54 UTC, ericswanson-dfinity commented
> I pasted the content of jira ticket into pr description

I appreciate the effort, but unfortunately it's not sufficient in this case.

The JIRA ticket describes a problem. Its purpose is to describe that problem in enough detail that the assignee can understand what's being asked for, and hopefully reproduce the problem.  It doesn't describe the cause of the problem because it can't: the cause isn't known at the time of writing of the JIRA ticket.

The PR description should describe the change and the reasoning behind it.   The PR author should understand their change well enough to describe what they did and why.  The PR description should give reviewers an idea of what they are looking at.  A succinct yet complete PR description will also demonstrate to reviewers that the PR author understands their own change.

2023-11-14 19:21 UTC, ericswanson-dfinity commented on src/canisters/frontend/ic-asset/src/asset/config.rs
> +        #[derivative(Default(value = "Some(true)"))]
An idea as to the underlying cause: this _removes_ the serde default, replacing it with an "impl Default" default.

What would you think about removing the `#[derivative(Default(value = "Some(true)"))]` as well?  At this level, we're interested in knowing what's in the config file rule, and None seems more accurate.

2024-03-04 16:06 UTC, sa-github-api commented
Dear @smallstepman,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/442) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2024-03-04 18:57 UTC, closed without merging

2024-03-04 18:57 UTC, ericswanson-dfinity commented
Replaced by https://github.com/dfinity/sdk/pull/3635