feat: specified_id in dfx.json
dfinity/sdk pull request #3565
Opened 2024-02-02 21:15 UTC by lwshang

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2024-02-03 00:50 UTC, ericswanson-dfinity requested changes

2024-02-03 00:50 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +Aside from passing `--specified-id` in `dfx deploy` and `dfx canister create`, `specified_id` can be set in `dfx.json`.
```suggestion
In addition to passing `--specified-id` in `dfx deploy` and `dfx canister create`, `specified_id` can be set in `dfx.json`.
```

2024-02-03 00:50 UTC, ericswanson-dfinity commented on src/dfx/src/commands/canister/create.rs
> +    /// This option overwrites the specified_id field in dfx.json.
```suggestion
    /// This option takes precedence over the specified_id field in dfx.json.
```

2024-02-03 00:50 UTC, ericswanson-dfinity commented on src/dfx/src/commands/deploy.rs
> +    /// This option overwrites the specified_id field in dfx.json.
or "supercedes"

```suggestion
    /// This option takes precedence over the specified_id field in dfx.json.
```

2024-02-03 00:50 UTC, ericswanson-dfinity commented on src/dfx/src/lib/operations/canister/create_canister.rs
> +    // Replace call_sender with wallet canister when necessary.
Can you say more about the "when necessary" part?  
I'm not following why this is related to `specified_id.is_none()`

2024-02-03 00:50 UTC, ericswanson-dfinity commented on src/dfx/src/lib/operations/canister/create_canister.rs
> +        if specified_id.is_none() && !no_wallet && !matches!(call_sender, CallSender::Wallet(_)) {
This expression has a lot of "not" in it.  I think we can rework it to be a little easier to follow, something like this (but please double-check the boolean logic):

```
if specified_id.is_some() || no_wallet || matches!(call_sender, Wallet...) {
    *call_sender
} else {
    match ...
}

```

2024-02-05 16:59 UTC, ericswanson-dfinity commented on src/dfx/src/lib/operations/canister/create_canister.rs
> +    // Replace call_sender with wallet canister unless:
This comment describes the predicate below, and the flow, but I'm still not quite following.  Can you describe _why_ we need to replace the call sender with the wallet?

2024-02-05 17:47 UTC, merged

2024-02-05 18:00 UTC, lwshang commented
As can be seen in the comment of `dfx canister --wallet` and `dfx deploy --wallet`:

> Specify a wallet canister id to perform the call.
If none specified, defaults to use the selected Identity's wallet canister.

That piece of code replacing `call_sender` was for this logic.

---

The `create_canister` method is now a complex shim which dispatch the creating canister logic to four underlying methods:
* reserve_canister_with_playground
* create_with_cycles_ledger
* create_with_management_canister
* create_with_wallet

There are many factors influence the dispatch:
* specify `--wallet`?
* set `--no-wallet`?
* which network: mainnet/playground/else?
* set `specified_id`?
* set `DFX_DISABLE_AUTO_WALLET`?
* `CYCLES_LEDGER_ENABLED`?
* maybe more...

The factors above are not orthogonal which makes it even more complicated.

We need a separate refactor PR to clear up and simplify the dispatch. I will file a Jira ticket.