feat: Update agent to dac18df939dd7e63295083a2a9b2d024cb9b0c71
dfinity/sdk pull request #3727
Opened 2024-04-24 22:18 UTC by adamspofford-dfinity

Includes the new `wasm_memory_limit` canister setting.

2024-04-25 14:37 UTC, ericswanson-dfinity requested changes
e2e

2024-04-25 14:40 UTC, lwshang commented on src/dfx-core/src/config/model/dfinity.rs
> +    pub wasm_memory_limit: Option<Byte>,
The type and schemar of this filed seems to be consistent with the existing `memory_allocation` field above.

But it is not consistent with the CLI flag `--wasm-memory-limit` below.

Can we have a unified description on the input format for this config field and the CLI flag?

2024-04-25 14:43 UTC, lwshang requested changes
A few suggestions:
1. Rename the PR title. It is far beyond upgrade agent-rs dependency.
2. Add tests

2024-04-26 14:46 UTC, lwshang commented on src/dfx-core/src/util/mod.rs
> +                pattern: Some("^[0-9]+( *([KkMmGgTtPpEeZzYy]i?)?B)?$".to_string()),
The e2e test shows that `8b` is allowed. But this regex denies it. The final `B` can be lowercase.

2024-04-26 14:51 UTC, lwshang commented on e2e/tests-dfx/update_settings.bash
> +@test "set wasm memory limit" {
What about expanding this test to also cover following paths?
* `dfx canister create --wasm-memory-limit`
* Setting the field in `dfx.json`

2024-04-26 17:14 UTC, lwshang approved these changes

2024-04-26 17:22 UTC, ericswanson-dfinity approved these changes

2024-04-26 18:14 UTC, merged