feat!: enable cycles ledger by default
dfinity/sdk pull request #3796
Opened 2024-06-19 09:01 UTC by sesi200

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2024-06-20 08:36 UTC, sesi200 commented on src/dfx/src/lib/cycles_ledger_types/mod.rs
> -// TODO(FI-1022): Import types from cycles ledger crate once available
Ticket was closed without action. There will be no such crate

2024-06-21 08:13 UTC, THLO approved these changes

2024-06-24 15:34 UTC, ericswanson-dfinity requested changes
As I understand it, the cycles ledger is now enabled all the time, not just by default.

2024-06-24 15:34 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +### feat!: enable cycles ledger support by default
```suggestion
### feat!: enable cycles ledger support unconditionally
```

2024-06-25 23:09 UTC, ericswanson-dfinity approved these changes

2024-06-26 07:46 UTC, merged