chore: release dfx 0.23.0
dfinity/sdk pull request #3855
Opened 2024-07-31 22:59 UTC by krpeacock

2024-08-05 19:08 UTC, ericswanson-dfinity requested changes
Looks like this PR should be to the release-0.23.0 branch

2024-08-05 20:23 UTC, ggreif commented
Could `moc` v0.11.3 be snuck into this release? https://dfinity.slack.com/archives/CGA566TPV/p1721510490346709. Just asking sheepishly...

2024-08-06 14:58 UTC, dfx-json commented
@ggreif that shouldn't be a problem. @krpeacock could you include moc 0.11.3 in a dfx `0.23.0-beta.1` ?

2024-08-21 12:39 UTC, sesi200 commented on CHANGELOG.md
> +# 0.23.0
Is this now correct? There's a 0.22.1 header further below

2024-11-15 22:59 UTC, closed without merging