fix: add browser warning message
dfinity/sdk pull request #4048
Opened 2024-12-20 19:28 UTC by adamspofford-dfinity

This adds a hidden div to frontend templates to display a message suggesting switching browsers when the page breaks, to solve the Safari problem in a different way from #4011.

2024-12-20 20:18 UTC, krpeacock commented
I don't like the implication that Safari is an unsupported browser - that would spook me as a developer

2024-12-20 20:22 UTC, adamspofford-dfinity commented
@krpeacock I mean, it's not an implication, it's straightforwardly true. An unadorned 'try switching browsers' would just lead to bug reports about it.

2024-12-20 20:27 UTC, krpeacock commented
It's not nuanced enough. There is no reason that Safari shouldn't work in production, and a developer seeing this message in their starter template would believe that the Internet Computer is incompatible with Safari, which makes the platform a non-starter

2024-12-20 20:30 UTC, krpeacock requested changes
Message is too blunt - I don't want to get in trouble for this

2025-01-06 18:54 UTC, krpeacock approved these changes

2025-01-06 19:28 UTC, merged